### ISSUE TITLE
测试中心设备无法启动 mqtt连不上

### ISSUE THREAD

**Issue by misureGitHub** [actorcloud/ActorCloud#332]

**Comment by misureGitHub** [comment]
<img width="1272" alt="启动pulsar报错很多" src="https://user-images.githubusercontent.com/45928599/63070026-0db69500-bf4c-11e9-9083-907d8b1092e2.png">
<img width="890" alt="actorCloud设备启动不了" src="https://user-images.githubusercontent.com/45928599/63070034-1909c080-bf4c-11e9-9b8d-12dc487d137e.png">

**Comment by zibuyu1995** [comment]
你需要登录admin设置 emqx broker 信息
![image](https://user-images.githubusercontent.com/17525759/63076294-4ca61400-bf67-11e9-8eed-890fe2962e9f.png)

**Comment by misureGitHub** [comment]
配置了，仍然启动不了

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/45928599/63087758-87b74000-bf85-11e9-90c8-adf72a02dd2a.png">
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/45928599/63087781-9140a800-bf85-11e9-982f-fc6342e8976f.png">

**Comment by misureGitHub** [comment]
可以连接上了，但是设备状态依然显示离线！
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/45928599/63091000-973b8680-bf8f-11e9-9edb-19e5106543d4.png">
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/45928599/63091030-b0443780-bf8f-11e9-8574-3c6e0a08b5e2.png">

**Comment by CrazyWisdom** [comment]
@zibuyu1995

**Comment by zibuyu1995** [comment]
@misureGitHub  Check that the eqmx webhook plugin is open
![image](https://user-images.githubusercontent.com/17525759/63136643-89c0e380-c005-11e9-8f6b-0cf24fef6da7.png)

**Comment by misureGitHub** [comment]
感谢您的指导
emqx_web_hook 插件是一直被我打开的
当我把emqx_auth_http 插件打开的时候，mqtt就连接不上了，下面截取了连接时候的日志
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/45928599/63137095-5f702580-c007-11e9-83eb-342e60dd1050.png">

<img width="811" alt="image" src="https://user-images.githubusercontent.com/45928599/63137155-96ded200-c007-11e9-8ddc-b5a380df1ab0.png">

**Comment by misureGitHub** [comment]
误点了close comment

**Comment by misureGitHub** [comment]
@zibuyu1995   麻烦解答下哈

**Comment by zibuyu1995** [comment]
@misureGitHub check emqx_auth_http plugin configuration:
![image](https://user-images.githubusercontent.com/17525759/63179539-eca29100-c07e-11e9-829a-16bf7032d35c.png)

**Comment by misureGitHub** [comment]
您好：
       修改了这个配置之后，问题依旧还是存在。
       
       还是，在测试中心，选择设备，点击启动的时候，会立刻提示连接失败，捕捉下面这log

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/45928599/63233872-2af9a500-c265-11e9-89f9-12605bd88753.png">


附件是我配置的一些关键文件，麻烦帮忙分析，需要什么我再提供。


[actorCloud和emqx关键配置.zip](https://github.com/actorcloud/ActorCloud/files/3513871/actorCloud.emqx.zip)

**Comment by misureGitHub** [comment]
@zibuyu1995   麻烦您帮忙看看

**Comment by zibuyu1995** [comment]
@misureGitHub resolve
