### ISSUE TITLE
pipenv run flask deploy: Error: No such command "deploy".

### ISSUE THREAD

**Issue by vinkdong** [actorcloud/ActorCloud#348]
Hi， flow doc installation, run pipenv run flask deploy got `Error: No such command "deploy".` error

```
Loading .env environment variables…
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try "flask --help" for help.

Error: No such command "deploy".
```

**Comment by vinkdong** [comment]
It works on my Mac fine but Centos did not work.
We'd better lock werkzeug version on Pipfile. higher version cant import `secure_filename ` .

**Comment by wilyfreddie** [comment]
Were you able to resolve this? I currently have the same issue.

I tried running using 
`pipenv run flask run`
and received this
`Loading .env environment variables…
 * Serving Flask app "manage" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 224-096-078`

Is this right?
